name: Update Files
on:
  repository_dispatch:
    types: [file-update]
  workflow_dispatch:
jobs:
  file-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: master
      - run: |
          .github/workflows/scripts/update_files.sh ${{ github.repository }}
      - name: Push updated docker compose file
        if: success()
        uses: test-room-7/action-update-file@v1
        with:
          branch: master
          file-path: |
            docker-compose.yml
          commit-msg: Update docker-compose.yml              
          github-token: ${{ secrets.MR_BUMP }}
